sudo: required
language: rust
cache: cargo
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
rust:
  - stable
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y mpd
  - /usr/bin/mpd --version
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH
  - cargo install --force rustfmt
script:
  - |
    travis-cargo build &&
    travis-cargo test
  - |
    cargo fmt -- --write-mode diff
  - |
    travis-cargo --only stable doc
after_success:
  - travis-cargo coveralls --no-sudo --verify
