[package]
authors = ["Konstantin Stepanov <me@kstep.me>"]
description = "A client library for MPD (music player daemon), like libmpdclient but in Rust"
documentation = "http://kstep.me/rust/doc/mpd/mpd/index.html"
homepage = "https://github.com/kstep/rust-mpd"
license = "MIT"
name = "mpd"
repository = "https://github.com/kstep/rust-mpd.git"
version = "0.0.8"

[dependencies]
bufstream = "0.1.1"
rustc-serialize = "0.3.16"
time = "0.1.34"

[dev-dependencies]
unix_socket = "0.5.0"
